name = "sac-confra-app"
pages_build_output_dir = "./"
compatibility_date = "2024-03-01"

[[d1_databases]]
binding = "DB"
database_name = "rsvp_db"
database_id = "754f7e44-5c3c-41dc-8ae3-a77434ff7e77"
